#!/usr/bin/env ruby

#
# terraforming-s3
#
# Usage:
#   aws s3api list-buckets | ./terraforming-s3
#

require "json"

json = ARGF.read
data = JSON.parse(json)

tfstate_s3_buckets = data['Buckets'].inject([]) do |result, bucket|
  tfstate_s3_bucket = {
    "aws_s3_bucket.#{bucket['Name']}" => {
      "type" => "aws_s3_bucket",
      "primary" => {
        "id" => bucket['Name'],
        "attributes" => {
          "acl" => "private",
          "bucket" => bucket['Name'],
          "id" => bucket['Name']
        }
      }
    }
  }

  result << tfstate_s3_bucket
  result
end

puts JSON.pretty_generate(tfstate_s3_buckets)
