require "oj"
require "ox"

require "aws-sdk-core"
require "erb"
require "json"
require "thor"
require "zlib"

require "terraforming/util"
require "terraforming/version"

require "terraforming/cli"

require "terraforming/provider"

require "terraforming/provider/aws"
require "terraforming/provider/aws/resource/auto_scaling_group"
require "terraforming/provider/aws/resource/db_parameter_group"
require "terraforming/provider/aws/resource/db_security_group"
require "terraforming/provider/aws/resource/db_subnet_group"
require "terraforming/provider/aws/resource/ec2"
require "terraforming/provider/aws/resource/eip"
require "terraforming/provider/aws/resource/elasti_cache_cluster"
require "terraforming/provider/aws/resource/elasti_cache_subnet_group"
require "terraforming/provider/aws/resource/elb"
require "terraforming/provider/aws/resource/iam_group"
require "terraforming/provider/aws/resource/iam_group_membership"
require "terraforming/provider/aws/resource/iam_group_policy"
require "terraforming/provider/aws/resource/iam_instance_profile"
require "terraforming/provider/aws/resource/iam_policy"
require "terraforming/provider/aws/resource/iam_role"
require "terraforming/provider/aws/resource/iam_role_policy"
require "terraforming/provider/aws/resource/iam_user"
require "terraforming/provider/aws/resource/iam_user_policy"
require "terraforming/provider/aws/resource/launch_configuration"
require "terraforming/provider/aws/resource/internet_gateway"
require "terraforming/provider/aws/resource/network_acl"
require "terraforming/provider/aws/resource/network_interface"
require "terraforming/provider/aws/resource/rds"
require "terraforming/provider/aws/resource/redshift"
require "terraforming/provider/aws/resource/route_table"
require "terraforming/provider/aws/resource/route_table_association"
require "terraforming/provider/aws/resource/route53_record"
require "terraforming/provider/aws/resource/route53_zone"
require "terraforming/provider/aws/resource/s3"
require "terraforming/provider/aws/resource/security_group"
require "terraforming/provider/aws/resource/subnet"
require "terraforming/provider/aws/resource/sqs"
require "terraforming/provider/aws/resource/vpc"
require "terraforming/provider/aws/resource/vpn_gateway"
