#!/usr/bin/env ruby

#
# terraforming-rds
#
# Usage:
#   aws rds describe-db-instances | ./terraforming-rds
#

require "terraforming"

generate_tfstate = ARGV.length > 0 && ARGV.shift == "--tfstate"

json = ARGF.read
data = JSON.parse(json)

puts generate_tfstate ? Terraforming::Resource::RDS.tfstate(data) : Terraforming::Resource::RDS.tf(data)
