#!/usr/bin/env ruby

#
# terraforming-sg
#
# Usage:
#   aws ec2 describe-security-groups | ./terraforming-sg
#

require "terraforming"

generate_tfstate = ARGV.length > 0 && ARGV.shift == "--tfstate"

json = ARGF.read
data = JSON.parse(json)

puts generate_tfstate ? Terraforming::Resource::SecurityGroup.tfstate(data) : Terraforming::Resource::SecurityGroup.tf(data)
