#!/usr/bin/env ruby

#
# terraforming-s3
#
# Usage:
#   aws s3api list-buckets | ./terraforming-s3 [--tfstate]
#

require "terraforming"

generate_tfstate = ARGV.length > 0 && ARGV.shift == "--tfstate"

json = ARGF.read
data = JSON.parse(json)

puts generate_tfstate ? Terraforming::Resource::S3.tfstate(data) : Terraforming::Resource::S3.tf(data)
