#!/usr/bin/env ruby

#
# terraforming-elb
#
# Usage:
#   aws elb describe-load-balancers | ./terraforming-elb
#

require "terraforming"

generate_tfstate = ARGV.length > 0 && ARGV.shift == "--tfstate"

json = ARGF.read
data = JSON.parse(json)

puts generate_tfstate ? Terraforming::Resource::ELB.tfstate(data) : Terraforming::Resource::ELB.tf(data)
