#!/usr/bin/env ruby

#
# terraforming-vpc
#
# Usage:
#   aws ec2 describe-vpcs | ./terraforming-vpc
#

require "terraforming"

generate_tfstate = ARGV.length > 0 && ARGV.shift == "--tfstate"

json = ARGF.read
data = JSON.parse(json)

puts generate_tfstate ? Terraforming::Resource::VPC.tfstate(data) : Terraforming::Resource::VPC.tf(data)
